# Declare variables to be passed into your templates.

image:
  repository: lloesche/valheim-server
  pullPolicy: IfNotPresent
  # The image builder only tags w/ 'latest'
  # This may be due to the non-determinism of updating the application internal to the container
  tag: "latest" 

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secrets:
  SERVER_PASS: "somerandompassword"
  SUPERVISOR_HTTP_PASS: ""

config:
  SERVER_NAME: "My Server"
  SERVER_PORT: "2456"
  WORLD_NAME: "Dedicated"
  SERVER_PUBLIC: "true"
  SERVER_ARGS: ""
  ADMINLIST_IDS: ""
  BANNEDLIST_IDS: ""
  PERMITTEDLIST_IDS: ""
  UPDATE_CRON: "*/15 * * * *"
  IDLE_DATAGRAM_WINDOW: "3"
  IDLE_DATAGRAM_MAX_COUNT: "30"
  UPDATE_IF_IDLE: "true"
  RESTART_CRON: "0 3 * * *"
  RESTART_IF_IDLE: "true"
  TZ: "America/Los_Angeles"
  BACKUPS: "true"
  BACKUPS_CRON: "0 */2 * * *"
  BACKUPS_DIRECTORY: "/config/backups"
  BACKUPS_MAX_AGE: "3"
  BACKUPS_MAX_COUNT: "0"
  BACKUPS_IF_IDLE: "true"
  BACKUPS_IDLE_GRACE_PERIOD: "3600"
  BACKUPS_ZIP: "true"
  PERMISSIONS_UMASK: "022"
  STEAMCMD_ARGS: "validate"
  VALHEIM_PLUS: "false"
  BEPINEX: "false"
  SUPERVISOR_HTTP:	false	
  SUPERVISOR_HTTP_PORT:	9001	
  SUPERVISOR_HTTP_USER:	admin	
  STATUS_HTTP	false: ""
  STATUS_HTTP_PORT:	80	
  STATUS_HTTP_CONF:	/config/httpd.conf	
  STATUS_HTTP_HTDOCS:	/opt/valheim/htdocs	
  SYSLOG_REMOTE_HOST:	""
  SYSLOG_REMOTE_PORT:	514	
  SYSLOG_REMOTE_AND_LOCAL:	true	
  PUID:	0	
  PGID:	0	

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

persistence:
  enabled: true
  #existingClaim:
  labels: {}
  annotations: {}
  accessModes: 
    - ReadWriteOnce
  # storageClass: "-"
  size: 10Gi

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 2456
  nodePort: 31000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 2000m
  #   memory: 4000Mi
  # requests:
  #   cpu: 500m
  #   memory: 2000Mi

nodeSelector: {}

tolerations: []

affinity: {}
