apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-valheim.fullname" . }}-configs
data:
{{- range $key, $value := .Values.config }}
  {{- if $value}}
  {{ $key }}: {{ $value | quote}}
  {{- end }}
{{- end }}