apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-valheim.fullname" . }}
  labels:
    {{- include "helm-valheim.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-valheim.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-valheim.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-valheim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: valheim
        securityContext:
            {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SERVER_PORT
          value: {{ .Values.service.port | quote }}
        - name: SERVER_NAME
          value: "Keller Valheim"
        - name: WORLD_NAME
          value: "Dedicated"
        - name: SERVER_PASS
          value: {{ .Values.config.password | quote }}
        ports:
        - containerPort: {{ .Values.service.port | int }}
          name: udp1
          protocol: UDP
        - containerPort: {{ .Values.service.port | int | add 1 }}
          name: udp2
          protocol: UDP
        - containerPort: {{ .Values.service.port | int | add 2 }}
          name: udp3
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /opt/valheim
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - "pidof valheim_server.x86_64 || exit 1"
        #   initialDelaySeconds: 120
        #   periodSeconds: 60
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - "pidof valheim_server.x86_64 || exit 1"
        #   initialDelaySeconds: 210
        #   periodSeconds: 60
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-{{ include "helm-valheim.fullname" . }}
      - name: data
        persistentVolumeClaim:
          claimName: data-{{ include "helm-valheim.fullname" . }}