apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-valheim.fullname" . }}-secrets
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{- if $value}}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}